---
repos:
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            args: [--in-place]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.26.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/timothycrosley/isort
      rev: 5.9.2
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 21.11b1
      hooks:
          - id: black
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.11.0
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==21.9b0]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 8f63da4
      hooks:
          - id: stylelint
            args: [--fix]
            additional_dependencies:
                - stylelint@14.1.0
                - stylelint-config-standard-scss@3.0.0
                - stylelint-scss@4.0.0
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.3
      hooks:
          - id: yamllint
    - repo: local
      hooks:
          - id: make-style
            name: Make style
            entry: python make_style.py
            language: python
            files: sass/*.scss
            additional_dependencies: [libsass]
